/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonNav: typeof import('./src/components/common-nav/index.vue')['default']
    MarkdownRender: typeof import('./src/components/markdown-render/index.vue')['default']
    Note: typeof import('./src/components/common-setting/note/index.vue')['default']
    ResizeTrigger: typeof import('./src/components/split/resize-trigger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharePopup: typeof import('./src/components/share-popup/index.vue')['default']
    ShortcutInput: typeof import('./src/components/shortcut-input/index.vue')['default']
    Split: typeof import('./src/components/split/index.vue')['default']
    Table: typeof import('./src/components/common-setting/table/index.vue')['default']
    TagNav: typeof import('./src/components/tag-nav/index.vue')['default']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    Terminal: typeof import('./src/components/terminal/index.vue')['default']
    TitleMenu: typeof import('./src/components/title-menu/index.vue')['default']
  }
}
